export const COLORS = {
  RED: '#ff5f5f',
  GREEN: '#256600',
  GREEN_LIGHT: '#D1E5E8',
  GREEN_SOFT: '#82b3c7',
  GREEN_DARK: '#4896a3',
  GREEN_SUCCESS: '#4a8f61',
  GREEN_MIDDLE: '#68c1b0',
  GREEN_LABEL: '#29b410',
  GREEN_NOTIFICATION: '#68c1b0',
  GREEN_CONTAINER: '#e3eff1',
  GREEN_LINK: '#68c1b0',
  GREEN_AVATAR: '#82B3C7',
  BLUE: '#4e73df',
  BLUE_MIDDLE: '#3b5998',
  BLUE_LABEL: '#03658e',
  BLUE_DARK_LABEL: '#05648d',
  BLUE_BUTTON: '#2f95dc',
  BLUE_LIGHT: '#5f92ff',
  BLUE_DARK: '#03658e',
  BLUE_LIGHT_SELECTED: '#f1fdff',
  BLUE_TITLE: '#05648d',
  BLUE_LIGHT_CONTAINER: '#ddebef',
  BLUE_NAME: '#03658e',
  GREY: '#f4f4f4',
  GREY_MIDDLE: '#d8d8d8',
  GREY_LIGHT: '#cccccc',
  GREY_ICON: '#222222',
  GREY_TITLE: '#888888',
  GREY_PLACEHOLDER: '#dddddd',
  GREY_SECTION: '#f6f6f6',
  GREY_LINE: '#eeeeee',
  GREY_LABEL: '#666666',
  GREY_QR: '#777',
  GREY_SEPARATOR: '#e5e5e5',
  GREY_SOFT: '#f6f6f6',
  DEFAULT_BACKGROUND: '#ccc',
  TAB_SELECTED: '#2f95dc',
  BLUE_NOTICE: '#2f95dc',
  WHITE: '#fff',
  BORDER: '#d6d7da',
  LINK: '#2e78b7',
  TRANSPARENT: 'transparent',
  GREY_CUSTOM: '#f2f3f7',
  ROW: '#FFF1C1',
  BLACK: '#000',
  BLACK_SOFT: '#444444',
  LINK_DARK: '#0645AD',
  BOTTOM_ELEMENT_CONTAINER: '#eee',
  TABLE_ALTERNATIVE_ROW: '#F7F6E7',
  TITLE: '#052738',
  VIOLET_LIGHT: '#f3f7ff',
  VIOLET: '#b4c9ff',
  PINK_LIGHT: '#fff4f6',
  PINK: '#f7b8bf',
  GOLD: '#cc9900',
  YELLOW: '#fdf2e0',
  YELLOW_DARK: '#D5a000',
};

export const STATUS = {
  SUCCESS: 'success',
  ERROR: 'error',
};

export const AVAILABLE_PLATFORMS = {
  IOS: 'ios',
  ANDROID: 'android',
};

export const ICONS = {
  HOME: {
    IOS: 'home',
    ANDROID: 'home',
  },
  INFO: {
    IOS: 'cogs',
    ANDROID: 'cogs',
  },
  PROFILE: {
    IOS: 'user-circle-o',
    ANDROID: 'user-circle-o',
  },
  MENU: {
    IOS: 'bars',
    ANDROID: 'bars',
  },
  CLOSE: {
    IOS: 'close',
    ANDROID: 'close',
  },
};

export const SCREENS = {
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  AUTH_SIGNUP_VERIFICATION_CODE: 'AUTH_SIGNUP_VERIFICATION_CODE',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOADING: 'AUTH_LOADING',
  AUTH_CHANGE_PASSWORD: 'AUTH_CHANGE_PASSWORD',
  AUTH_RESET_PASSWORD: 'AUTH_RESET_PASSWORD',
  AUTH_RESET_PASSWORD_EMAIL_SENT: 'AUTH_RESET_PASSWORD_EMAIL_SENT',
  AUTH_CONFIRM_RESET_PASSWORD: 'AUTH_CONFIRM_RESET_PASSWORD',
  AUTH_TERMS_AND_CONDITIONS: 'AUTH_TERMS_AND_CONDITIONS',
  AUTH_PRIVACY_POLICY: 'AUTH_PRIVACY_POLICY',
  AUTH_PENDING_APPROVAL: 'AUTH_PENDING_APPROVAL',
  INSTALLATION_WIZARD: 'INSTALLATION_WIZARD',
  NOTIFICATIONS: 'NOTIFICATIONS',
  NOTIFICATION_DETAILS: 'NOTIFICATION_DETAILS',
  PATIENT_LOADING: 'PATIENT_LOADING',
  PATIENT_DASHBOARD: 'PATIENT_DASHBOARD',
  PATIENT_WELCOME: 'PATIENT_WELCOME',
  PATIENT_PROFILE_CREATION: 'PATIENT_PROFILE_CREATION',
  PATIENT_PROFILE: 'PATIENT_PROFILE',
  PATIENT_PROFILE_PICTURE: 'PATIENT_PROFILE_PICTURE',
  PATIENT_CHANGE_PICTURE: 'PATIENT_CHANGE_PICTURE',
  PATIENT_CHECKOUT_TRANSITION: 'PATIENT_CHECKOUT_TRANSITION',
  PATIENT_HISTORY: 'PATIENT_HISTORY',
  PATIENT_SESSION_DETAILS: 'PATIENT_SESSION_DETAILS',
  CAREGIVER_LOADING: 'CAREGIVER_LOADING',
  CAREGIVER_DASHBOARD: 'CAREGIVER_DASHBOARD',
  CAREGIVER_NOTIFICATIONS: 'CAREGIVER_NOTIFICATIONS',
  CAREGIVER_CREATE_PROFILE: 'CAREGIVER_CREATE_PROFILE',
  CAREGIVER_EDIT_PROFILE: 'CAREGIVER_EDIT_PROFILE',
  CAREGIVER_UPLOAD_PICTURE: 'CAREGIVER_UPLOAD_PICTURE',
  CAREGIVER_INSTALLATION_WIZARD: 'CAREGIVER_INSTALLATION_WIZARD',
  CAREGIVER_PATIENTS: 'CAREGIVER_PATIENTS',
  CAREGIVER_PATIENT_INVITES: 'CAREGIVER_PATIENT_INVITES',
  CAREGIVER_PATIENT_DASHBOARD: 'CAREGIVER_PATIENT_DASHBOARD',
  CAREGIVER_PATIENT_PERSONAL_INFORMATION: 'CAREGIVER_PERSONAL_INFORMATION',
  CAREGIVER_PATIENT_PROFILE_EDITION: 'CAREGIVER_PATIENT_PROFILE_EDITION',
  CAREGIVER_PATIENT_ADD: 'CAREGIVER_PATIENT_ADD',
  CAREGIVER_PATIENT_HISTORY: 'CAREGIVER_PATIENT_HISTORY',
  CAREGIVER_CLAIM_SESSION_DETAILS: 'CAREGIVER_CLAIM_SESSION_DETAILS',
  CAREGIVER_CLAIM_SESSION_ASSOCIATE_TO: 'CAREGIVER_CLAIM_SESSION_ASSOCIATE_TO',
  CAREGIVER_PATIENT_SESSION_DETAILS: 'CAREGIVER_PATIENT_SESSION_DETAILS',
  PAIR_DEVICE_QR_SCAN: 'PAIR_DEVICE_QR_SCAN',
  PAIR_DEVICE_SET_MANUALLY: 'PAIR_DEVICE_SET_MANUALLY',
  PAIR_DEVICE_DETECTED: 'PAIR_DEVICE_DETECTED',
  PAIR_DEVICE_WIFI_CONNECTION: 'PAIR_DEVICE_WIFI_CONNECTION',
  PAIR_DEVICE_NAME: 'PAIR_DEVICE_NAME',
  PAIR_SUCCESSFULLY_PAIRED: 'PAIR_SUCCESSFULLY_PAIRED',
  DEVICES_LIST: 'DEVICES_LIST',
  DEVICE_DETAILS: 'DEVICE_DETAILS',
  DEVICE_SETTINGS: 'DEVICE_SETTINGS',
  SETTINGS: 'SETTINGS',
};

export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  PUSH_NOTIFICATION_TOKEN: 'PUSH_NOTIFICATION_TOKEN',
  USER_TYPE: 'USER_TYPE',
  CAMERA_PERMISSION: 'CAMERA_PERMISSION',
};

export const NAVIGATOR = {
  AUTH: 'Auth',
  APP: 'App',
};

export const BUTTON_TYPES = {
  PRIMARY: COLORS.BLUE_MIDDLE,
  SECONDARY: COLORS.GREEN_LIGHT,
  ALTERNATIVE: COLORS.BLUE_NOTICE,
  INFO: COLORS.INFO,
  BLACK: COLORS.BLACK,
  DISABLED: COLORS.GREY_LIGHT,
  BACK: COLORS.GREEN_LIGHT,
  CONTINUE: COLORS.GREEN_DARK,
};

export const CODE_ERRORS = {
  USER_NOT_CONFIRMED: 'UserNotConfirmedException',
  UNKNOWN_ERROR: 'Unknown error.',
  NEW_PASSWORD_REQUIRED: 'NEW_PASSWORD_REQUIRED',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  HISTORY_NO_MORE: 'HISTORY_NO_MORE',
};

export const STATES = {
  SESSION_NOT_ACTIVE: 'SESSION_NOT_ACTIVE',
  SESSION_ASSIGNED: 'SESSION_ASSIGNED',
  REQUIRES_CHECKOUT: 'REQUIRES_CHECKOUT',
};

export const USER_TYPES = {
  PATIENT: 'patient',
  CAREGIVER: 'caregiver',
};

export const INPUT_SIZES = {
  LARGE: '90%',
  MEDIUM: '50%',
  SMALL: '25%',
  THIRD: '33%',
};

export const UNITS = {
  LBS: 'lbs',
  FT: 'ft',
};

export const API_MODELS = {
  CAREGIVER: 'caregiver',
  PATIENT: 'patient',
  PATIENTS: 'patients',
  DISEASES: 'diseases',
  SESSIONS: 'sessions',
  USERS: 'users',
  NOTIFICATIONS: 'notifications',
  SIGN_UP: 'signup',
  INVITATIONS: 'invitations',
  DEVICES: 'devices',
  INTERVENTIONS: 'interventions',
  IMAGES: 'images',
  FILES: 'files',
};

export const KEYBOARD_TYPES = {
  DEFAULT: 'default',
  NUMERIC: 'number-pad',
  EMAIL: 'email-address',
  PHONE: 'phone-pad',
};

export const GENDERS = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
};

export const APP_TITLE = 'TRUELOO';

export const BUTTON_SIZES = {
  MIDDLE: '45%',
  SMALL: '60%',
  STANDARD: '80%',
  LARGE: '90%',
  X_LARGE: '96%',
  X_SMALL: '45%',
};

export const BUTTON_HEIGHT = {
  STANDARD: '60px',
  X_LARGE: '86px',
};

export const FONT_SIZES = {
  SMALL: '12px',
  MEDIUM: '16px',
  MEDIUM_UPPER: '18px',
  LARGE: '22px',
};

export const NOTIFICATION_TIMEOUT = 60000;

export const FONT_FAMILY = {
  MAIN: 'Roboto',
  CENTURY_GOTHIC: 'Century Gothic',
};

export const MESSAGE_TYPES = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  WARNING: 'WARNING',
};

export const REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
};

export const NOTIFICATION_TYPES = {
  SEPARATOR: 'SEPARATOR',
  PATIENT_HAS_NO_DEVICES: 'PATIENT_HAS_NO_DEVICES',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  INVITATION_REMINDER: 'INVITATION_REMINDER',
  UNCLAIMED_SESSION: 'UNCLAIMED_SESSION',
  DEVICE_MALFUNCTION: 'DEVICE_MALFUNCTION',
  SESSION_TOO_LONG: 'SESSION_TOO_LONG',
  INTERVENTION: 'INTERVENTION',
  INTERVENTION_ACTION_REQUIRED: 'INTERVENTION_ACTION_REQUIRED',
  STOOL_CONSISTENCY_CONSTIPATION: 'STOOL_CONSISTENCY_CONSTIPATION',
  STOOL_CONSISTENCY_LACKING_FIBER: 'STOOL_CONSISTENCY_LACKING_FIBER',
  STOOL_CONSISTENCY_MILD_DIARRHEA: 'STOOL_CONSISTENCY_MILD_DIARRHEA',
  STOOL_CONSISTENCY_DIARRHEA: 'STOOL_CONSISTENCY_DIARRHEA',
  STOOL_COLOR_GREEN: 'STOOL_COLOR_GREEN',
  STOOL_COLOR_BLACK: 'STOOL_COLOR_BLACK',
  STOOL_COLOR_PALE: 'STOOL_COLOR_PALE',
  STOOL_COLOR_YELLOW: 'STOOL_COLOR_YELLOW',
  STOOL_COLOR_RED: 'STOOL_COLOR_RED',
  URINE_COLOR_4: 'URINE_COLOR_4',
  URINE_COLOR_5: 'URINE_COLOR_5',
  URINE_COLOR_6: 'URINE_COLOR_6',
  URINE_COLOR_7: 'URINE_COLOR_7',
  URINE_COLOR_8: 'URINE_COLOR_8',
  DARKER_URINE_DETECTED: 'DARKER_URINE_DETECTED',
};

export const DEVICE_STATUSES = {
  IN_USE: 'IN_USE',
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  UNDEFINED: 'UNDEFINED',
};

export const ACTIONS = {
  EDIT: 'EDIT',
  SAVE: 'SAVE',
};

export const PERMISSIONS = {
  READY: 'READY',
  PENDING_AUTHORIZATION: 'PENDING_AUTHORIZATION',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  BLOCKED: 'blocked',
  GRANTED: 'granted',
};

export const INDICATOR_STATUSES = {
  OK: 'OK',
  BAD: 'BAD',
  WARNING: 'WARNING',
};

export const REGISTER_TYPES = {
  INTERVENTION: 'INTERVENTION',
  SESSION: 'SESSION',
};

export const AUTO_COMPLETE_TYPES = {
  EMAIL: 'email',
};

export const TEXT_CONTENT_TYPES = {
  EMAIL_ADDRESS: 'emailAddress',
  USER_NAME: 'username',
  PASSWORD: 'password',
};

export const RETURN_KEY_TYPES = {
  GO: 'go',
  DONE: 'done',
};

export const DATE_TIME_FORMATS = {
  MM_DD_YYYY: 'MM-DD-YYYY',
  MMM_D_YYYY: 'MMM D, YYYY',
};

export const GUEST = 'Guest';

export const DATE_FILTERS = {
  TODAY: 'Today',
  YESTERDAY: 'Yesterday',
  LAST_WEEK: 'This Week',
};

export const STYLES = {
  TEXT: {
    TRANSFORMATION: {
      UPPERCASE: 'uppercase',
      CAPITALIZE: 'capitalize',
      NONE: 'none',
    },
    ALIGN: {
      LEFT: 'left',
      CENTER: 'center',
    },
  },
  FONT: {
    WEIGHT: {
      BOLD: 'bold',
    },
    SIZE: {
      MEDIUM: '18px',
      MEDIUM_UPPER: '20px',
    },
  },
  MARGINGS: {
    10: '10px',
    20: '20px',
    30: '30px',
    40: '40px',
    80: '80px',
    100: '100px',
    140: '140px',
    200: '200px',
  },
};
