/*
 * Actions
 */

export const PLANETS_BEGIN = 'PLANETS_BEGIN';
export const PLANETS_SUCCESS = 'PLANETS_SUCCESS';
export const PLANETS_FAILED = 'PLANETS_FAILED';

export const PLANET_DETAILS_BEGIN = 'PLANET_DETAILS_BEGIN';
export const PLANET_DETAILS_SUCCESS = 'PLANET_DETAILS_SUCCESS';
export const PLANET_DETAILS_FAILED = 'PLANET_DETAILS_FAILED';
